### PR TITLE
Start add-birthday-file

### PR DESCRIPTION
**Pull request by sjku1**
addresses issue #10 by adding a birthday.txt file containing the birthday of each team member.

### CODE REVIEW

**Comment by Amal-m20** [comment]
Hi @sjku1 my birthday is January 5, 1998

**Comment by sjku1** [comment]
@shadow12ac got it! thanks! also, could you please review my pull request?

**Comment by Amal-m20** [comment]
Hi @sjku1 could you also add the year each group member was born.

**Comment by Bakainkorp** [comment]
@sjku1 My birth year is 1995.

**Pull request merged**
