### PR TITLE
Start dream_job

### PR DESCRIPTION
**Pull request by Amal-m20**

### CODE REVIEW

**Comment by Amal-m20** [comment]
I'm  starting to work on #9

**Comment by sjku1** [comment]
Hey @shadow12ac , my dream job is being a software engineer.

**Comment by Bakainkorp** [comment]
Hey @shadow12ac, my dream job is being a video game developer..

**Comment by Amal-m20** [comment]
Hey @Bakainkorp thank you and can you please review my pull request

**Comment by Bakainkorp** [comment]
This is good. I'll send out the merge.

**Pull request merged**
